### ISSUE TITLE
How do I add a cluster?

### ISSUE THREAD

**Issue by florianeichin** [ccc13/etcd-rs#1]
How do I add a cluster to the client?

```
let etcd_adress = vec![
        "127.0.0.1:23791".to_owned(),
        "127.0.0.1:23792".to_owned(),
        "127.0.0.1:23793".to_owned(),
    ]
Client::builder().endpoints(etcd_adress.clone()).build()
```

returns: `RpcFailure(RpcStatus { status: Unavailable, details: Some("Name resolution failure") })`

but `Client::builder().add_endpoint( "127.0.0.1:23791").build() ` with each of the upper ips works.

FYI this is the docker-compose I use to start the cluster:

```
version: '3'

services:

  etcd1:
    image: quay.io/coreos/etcd:latest
    environment:
            ETCD_NAME: node1

            ETCD_ADVERTISE_CLIENT_URLS: http://etcd1:2379
            ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379

            ETCD_INITIAL_ADVERTISE_PEER_URLS: http://etcd1:2380
            ETCD_LISTEN_PEER_URLS: http://0.0.0.0:2380

            ETCD_DATA_DIR: /etcd-data/etcd1.etcd
            ETCDCTL_API: 3
            ETCD_DEBUG: 1
            
            ETCD_INITIAL_CLUSTER: node3=http://etcd3:2380,node1=http://etcd1:2380,node2=http://etcd2:2380
            ETCD_INITIAL_CLUSTER_STATE: new
            ETCD_INITIAL_CLUSTER_TOKEN: etcd-ftw           
    ports:
      - 23791:2379
      - 23801:2380


  etcd2:
    image: quay.io/coreos/etcd:latest
    environment:
            ETCD_NAME: node2

            ETCD_INITIAL_ADVERTISE_PEER_URLS: http://etcd2:2380
            ETCD_LISTEN_PEER_URLS: http://0.0.0.0:2380

            ETCD_ADVERTISE_CLIENT_URLS: http://etcd2:2379
            ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
            
            ETCD_DATA_DIR: /etcd-data/etcd2.etcd
            ETCDCTL_API: 3
            ETCD_DEBUG: 1

            ETCD_INITIAL_CLUSTER: node3=http://etcd3:2380,node1=http://etcd1:2380,node2=http://etcd2:2380
            ETCD_INITIAL_CLUSTER_STATE: new
            ETCD_INITIAL_CLUSTER_TOKEN: etcd-ftw
    ports:
      - 23792:2379
      - 23802:2380


  etcd3:
    image: quay.io/coreos/etcd:latest
    environment:
            ETCD_NAME: node3

            ETCD_INITIAL_ADVERTISE_PEER_URLS: http://etcd3:2380
            ETCD_LISTEN_PEER_URLS: http://0.0.0.0:2380
            
            ETCD_ADVERTISE_CLIENT_URLS: http://etcd3:2379
            ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
            

            ETCD_DATA_DIR: /etcd-data/etcd3.etcd
            ETCDCTL_API: 3
            ETCD_DEBUG: 1
            
            ETCD_INITIAL_CLUSTER: node3=http://etcd3:2380,node1=http://etcd1:2380,node2=http://etcd2:2380
            ETCD_INITIAL_CLUSTER_STATE: new
            ETCD_INITIAL_CLUSTER_TOKEN: etcd-ftw
    ports:
      - 23793:2379
      - 23803:2380
```

Thanks in Advance!
